### ISSUE TITLE
perfdata not working.

### ISSUE THREAD

**Issue by fromanm1** [Tylan/check_snmp_iftraffic#2]
the perfdata output only shows the "inSpeed", all other perfdata output is missing.

Example:
OK - Average IN: 0.29MBps (0.23%), Average OUT: 0.29MBps (0.23%) Total RX: 4014.20MBytes, Total TX: 4014.20MBytes|**inSpeed=0.29MBps;;;0;1000**

**Comment by Tylan** [comment]
Hi - can you provide the exact command line command with options you used so I may try to replicate?

**Comment by Tylan** [comment]
Actually, I found the error and corrected it.  Please grab the update here.  Re-open if still an issue but should be good to go now.

https://github.com/Tylan/check_snmp_iftraffic/blob/main/check_snmp_iftraffic

**Comment by fromanm1** [comment]
> Actually, I found the error and corrected it. Please grab the update here. Re-open if still an issue but should be good to go now.
> 
> https://github.com/Tylan/check_snmp_iftraffic/blob/main/check_snmp_iftraffic

works perfectly now! 

thank you Tylan!
